swipe:
  3:
    up:
      command: "quickshell ipc -p /home/caseyw/.config/quickshell call drawers toggle workspacemanager"
    down:
      command: "quickshell ipc -p /home/caseyw/.config/quickshell call drawers toggle workspacemanager"

threshold:
  swipe: 0.5

interval:
  swipe: 0.5